const AVAILABLE_COLORS = "GET_AVAILABLE_COLORS";

const AVAILABLE_LEVELS = "GET_AVAILABLE_LEVELS";

const LEVEL_OF_GAME = "SET_LEVEL_OF_GAME";

const GENERATE_TARGET_COLORS = "GENERATE_TARGET_COLORS";


export { 
	AVAILABLE_COLORS, 
	AVAILABLE_LEVELS, 
	LEVEL_OF_GAME, 
	GENERATE_TARGET_COLORS 
};
